---
driver:
  name: terraform
  variables:
    region: "<%= ENV['AWS_DEFAULT_REGION'] %>"
    instance_type: "<%= ENV['AWS_DEFAULT_INSTANCE_TYPE'] %>"
    ssh_security_group_cidr: "<%= ENV['SSH_SG_CIDR'] %>"

provisioner:
  name: terraform

platforms:
  - name: setup

verifier:
  name: terraform
  format: json  
  output: aws_results.json
  groups:
    - name: default

suites:
  - name: minimal
    driver:
      root_module_directory: "./test/integration/minimal/build/"
    verifier:
      inspec_tests:
        - path: "./test/integration/minimal/verify"

  - name: cis
    driver:
      variables:
        prefix: "cis"
      root_module_directory: "./test/integration/cis/build/"

    verifier:
      inspec_tests:
        - git: https://github.com/mitre/cis-aws-foundations-v1.1.0-baseline.git
