---
driver:
  name: terraform
  variables:
    access_key: "<%= ENV['AWS_ACCESS_KEY_ID'] %>"
    secret_key: "<%= ENV['AWS_SECRET_ACCESS_KEY'] %>"
    region: "<%= ENV['AWS_DEFAULT_REGION'] %>"

provisioner:
  name: terraform

platforms:
  - name: setup

verifier:
  name: terraform
  format: cli
  groups:
    - name: default

suites:
  - name: minimal
    driver:
      root_module_directory: "./test/integration/minimal/build/"
    verifier:
      inspec_tests:
        - path: "./test/integration/minimal/verify"

  - name: cis
    driver:
      variables:
        prefix: "cis"
      root_module_directory: "./test/integration/cis/build/"
    verifier:
      inspec_tests:
        - git: https://github.com/aaronlippold/cis-aws-foundations-baseline.git
        # - path: "./test/integration/cis/cis-aws-foundations-baseline"
      # controls:
      #   - cis-aws-foundations-2.5
